In [3]:
#Creation of numpy array

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [6]:
#Math Operations on datatype array

import numpy as np

a= np.array([[3,5],[4,6]],dtype=np.float64)
b=np.array([[1,4],[2,5]],dtype=np.float64)


print(sum(b))
print(a+2)



[3. 9.]
[[5. 7.]
 [6. 8.]]


In [8]:
#Broadcasting in numpy for 1D array

import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr+3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
#broadcasting in numpy for 2D array

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a+b)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [11]:
#broadcasting in numpy for conditional statements

a = np.array([15,20,25])
b = np.array(["Minor","Adult"])

res = np.where(a<18,b[0],b[1])
print(res)


['Minor' 'Adult' 'Adult']


In [12]:
#Broadcasting in numpy for Matrix multiplication

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

res = a * b
print(res)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
